### ISSUE TITLE
Twitter: ElasticSearch Templates & Alias

### ISSUE THREAD

**Issue by gustavorps** [Labic/hash-api-py#2]
Use this issue to track and discuss about implementation with Twitter and ElasticSearch
## TO-DO
 - [ ] Most retweeted tweets by keywords with *stopwords*, `keywords`  and `created_at` interval filters, and *sort* by `created_at`
 - [ ] Tweets by keywords with *stopwords*, `keywords`  and `created_at` interval filters, and *sort* by `created_at`
 - [ ] Images by keywords with *stopwords*, `keywords`  and `created_at` interval filters, and *sort* by `created_at`
